<?php

/**
 * @author Jasman <jasman@ihsana.com>
 * @copyright Ihsana IT Solution 2020
 * @license Commercial License
 * 
 */

defined("IHS_EXEC") or die("Silence is golden");

class ShowIcon
{

    function dashicons()
    {
        $dashicons[] = array('var' => 'menu', 'val' => '');
        $dashicons[] = array('var' => 'admin-site', 'val' => '');
        $dashicons[] = array('var' => 'dashboard', 'val' => '');
        $dashicons[] = array('var' => 'admin-post', 'val' => '');
        $dashicons[] = array('var' => 'admin-media', 'val' => '');
        $dashicons[] = array('var' => 'admin-links', 'val' => '');
        $dashicons[] = array('var' => 'admin-page', 'val' => '');
        $dashicons[] = array('var' => 'admin-comments', 'val' => '');
        $dashicons[] = array('var' => 'admin-appearance', 'val' => '');
        $dashicons[] = array('var' => 'admin-plugins', 'val' => '');
        $dashicons[] = array('var' => 'admin-users', 'val' => '');
        $dashicons[] = array('var' => 'admin-tools', 'val' => '');
        $dashicons[] = array('var' => 'admin-settings', 'val' => '');
        $dashicons[] = array('var' => 'admin-network', 'val' => '');
        $dashicons[] = array('var' => 'admin-home', 'val' => '');
        $dashicons[] = array('var' => 'admin-generic', 'val' => '');
        $dashicons[] = array('var' => 'admin-collapse', 'val' => '');
        $dashicons[] = array('var' => 'filter', 'val' => '');
        $dashicons[] = array('var' => 'admin-customizer', 'val' => '');
        $dashicons[] = array('var' => 'admin-multisite', 'val' => '');
        $dashicons[] = array('var' => 'welcome-write-blog', 'val' => '');
        $dashicons[] = array('var' => 'welcome-add-page', 'val' => '');
        $dashicons[] = array('var' => 'welcome-view-site', 'val' => '');
        $dashicons[] = array('var' => 'welcome-widgets-menus', 'val' => '');
        $dashicons[] = array('var' => 'welcome-comments', 'val' => '');
        $dashicons[] = array('var' => 'welcome-learn-more', 'val' => '');
        $dashicons[] = array('var' => 'format-aside', 'val' => '');
        $dashicons[] = array('var' => 'format-image', 'val' => '');
        $dashicons[] = array('var' => 'format-gallery', 'val' => '');
        $dashicons[] = array('var' => 'format-video', 'val' => '');
        $dashicons[] = array('var' => 'format-status', 'val' => '');
        $dashicons[] = array('var' => 'format-quote', 'val' => '');
        $dashicons[] = array('var' => 'format-chat', 'val' => '');
        $dashicons[] = array('var' => 'format-audio', 'val' => '');
        $dashicons[] = array('var' => 'camera', 'val' => '');
        $dashicons[] = array('var' => 'images-alt', 'val' => '');
        $dashicons[] = array('var' => 'images-alt2', 'val' => '');
        $dashicons[] = array('var' => 'video-alt', 'val' => '');
        $dashicons[] = array('var' => 'video-alt2', 'val' => '');
        $dashicons[] = array('var' => 'video-alt3', 'val' => '');
        $dashicons[] = array('var' => 'media-archive', 'val' => '');
        $dashicons[] = array('var' => 'media-audio', 'val' => '');
        $dashicons[] = array('var' => 'media-code', 'val' => '');
        $dashicons[] = array('var' => 'media-default', 'val' => '');
        $dashicons[] = array('var' => 'media-document', 'val' => '');
        $dashicons[] = array('var' => 'media-interactive', 'val' => '');
        $dashicons[] = array('var' => 'media-spreadsheet', 'val' => '');
        $dashicons[] = array('var' => 'media-text', 'val' => '');
        $dashicons[] = array('var' => 'media-video', 'val' => '');
        $dashicons[] = array('var' => 'playlist-audio', 'val' => '');
        $dashicons[] = array('var' => 'playlist-video', 'val' => '');
        $dashicons[] = array('var' => 'controls-play', 'val' => '');
        $dashicons[] = array('var' => 'controls-pause', 'val' => '');
        $dashicons[] = array('var' => 'controls-forward', 'val' => '');
        $dashicons[] = array('var' => 'controls-skipforward', 'val' => '');
        $dashicons[] = array('var' => 'controls-back', 'val' => '');
        $dashicons[] = array('var' => 'controls-skipback', 'val' => '');
        $dashicons[] = array('var' => 'controls-repeat', 'val' => '');
        $dashicons[] = array('var' => 'controls-volumeon', 'val' => '');
        $dashicons[] = array('var' => 'controls-volumeoff', 'val' => '');
        $dashicons[] = array('var' => 'image-crop', 'val' => '');
        $dashicons[] = array('var' => 'image-rotate', 'val' => '');
        $dashicons[] = array('var' => 'image-rotate-left', 'val' => '');
        $dashicons[] = array('var' => 'image-rotate-right', 'val' => '');
        $dashicons[] = array('var' => 'image-flip-vertical', 'val' => '');
        $dashicons[] = array('var' => 'image-flip-horizontal', 'val' => '');
        $dashicons[] = array('var' => 'image-filter', 'val' => '');
        $dashicons[] = array('var' => 'undo', 'val' => '');
        $dashicons[] = array('var' => 'redo', 'val' => '');
        $dashicons[] = array('var' => 'editor-bold', 'val' => '');
        $dashicons[] = array('var' => 'editor-italic', 'val' => '');
        $dashicons[] = array('var' => 'editor-ul', 'val' => '');
        $dashicons[] = array('var' => 'editor-ol', 'val' => '');
        $dashicons[] = array('var' => 'editor-quote', 'val' => '');
        $dashicons[] = array('var' => 'editor-alignleft', 'val' => '');
        $dashicons[] = array('var' => 'editor-aligncenter', 'val' => '');
        $dashicons[] = array('var' => 'editor-alignright', 'val' => '');
        $dashicons[] = array('var' => 'editor-insertmore', 'val' => '');
        $dashicons[] = array('var' => 'editor-spellcheck', 'val' => '');
        $dashicons[] = array('var' => 'editor-expand', 'val' => '');
        $dashicons[] = array('var' => 'editor-contract', 'val' => '');
        $dashicons[] = array('var' => 'editor-kitchensink', 'val' => '');
        $dashicons[] = array('var' => 'editor-underline', 'val' => '');
        $dashicons[] = array('var' => 'editor-justify', 'val' => '');
        $dashicons[] = array('var' => 'editor-textcolor', 'val' => '');
        $dashicons[] = array('var' => 'editor-paste-word', 'val' => '');
        $dashicons[] = array('var' => 'editor-paste-text', 'val' => '');
        $dashicons[] = array('var' => 'editor-removeformatting', 'val' => '');
        $dashicons[] = array('var' => 'editor-video', 'val' => '');
        $dashicons[] = array('var' => 'editor-customchar', 'val' => '');
        $dashicons[] = array('var' => 'editor-outdent', 'val' => '');
        $dashicons[] = array('var' => 'editor-indent', 'val' => '');
        $dashicons[] = array('var' => 'editor-help', 'val' => '');
        $dashicons[] = array('var' => 'editor-strikethrough', 'val' => '');
        $dashicons[] = array('var' => 'editor-unlink', 'val' => '');
        $dashicons[] = array('var' => 'editor-rtl', 'val' => '');
        $dashicons[] = array('var' => 'editor-break', 'val' => '');
        $dashicons[] = array('var' => 'editor-code', 'val' => '');
        $dashicons[] = array('var' => 'editor-paragraph', 'val' => '');
        $dashicons[] = array('var' => 'editor-table', 'val' => '');
        $dashicons[] = array('var' => 'align-left', 'val' => '');
        $dashicons[] = array('var' => 'align-right', 'val' => '');
        $dashicons[] = array('var' => 'align-center', 'val' => '');
        $dashicons[] = array('var' => 'align-none', 'val' => '');
        $dashicons[] = array('var' => 'lock', 'val' => '');
        $dashicons[] = array('var' => 'unlock', 'val' => '');
        $dashicons[] = array('var' => 'calendar', 'val' => '');
        $dashicons[] = array('var' => 'calendar-alt', 'val' => '');
        $dashicons[] = array('var' => 'visibility', 'val' => '');
        $dashicons[] = array('var' => 'hidden', 'val' => '');
        $dashicons[] = array('var' => 'post-status', 'val' => '');
        $dashicons[] = array('var' => 'edit', 'val' => '');
        $dashicons[] = array('var' => 'trash', 'val' => '');
        $dashicons[] = array('var' => 'sticky', 'val' => '');
        $dashicons[] = array('var' => 'external', 'val' => '');
        $dashicons[] = array('var' => 'arrow-up', 'val' => '');
        $dashicons[] = array('var' => 'arrow-down', 'val' => '');
        $dashicons[] = array('var' => 'arrow-right', 'val' => '');
        $dashicons[] = array('var' => 'arrow-left', 'val' => '');
        $dashicons[] = array('var' => 'arrow-up-alt', 'val' => '');
        $dashicons[] = array('var' => 'arrow-down-alt', 'val' => '');
        $dashicons[] = array('var' => 'arrow-right-alt', 'val' => '');
        $dashicons[] = array('var' => 'arrow-left-alt', 'val' => '');
        $dashicons[] = array('var' => 'arrow-up-alt2', 'val' => '');
        $dashicons[] = array('var' => 'arrow-down-alt2', 'val' => '');
        $dashicons[] = array('var' => 'arrow-right-alt2', 'val' => '');
        $dashicons[] = array('var' => 'arrow-left-alt2', 'val' => '');
        $dashicons[] = array('var' => 'sort', 'val' => '');
        $dashicons[] = array('var' => 'leftright', 'val' => '');
        $dashicons[] = array('var' => 'randomize', 'val' => '');
        $dashicons[] = array('var' => 'list-view', 'val' => '');
        $dashicons[] = array('var' => 'exerpt-view', 'val' => '');
        $dashicons[] = array('var' => 'grid-view', 'val' => '');
        $dashicons[] = array('var' => 'share', 'val' => '');
        $dashicons[] = array('var' => 'share-alt', 'val' => '');
        $dashicons[] = array('var' => 'share-alt2', 'val' => '');
        $dashicons[] = array('var' => 'twitter', 'val' => '');
        $dashicons[] = array('var' => 'rss', 'val' => '');
        $dashicons[] = array('var' => 'email', 'val' => '');
        $dashicons[] = array('var' => 'email-alt', 'val' => '');
        $dashicons[] = array('var' => 'facebook', 'val' => '');
        $dashicons[] = array('var' => 'facebook-alt', 'val' => '');
        $dashicons[] = array('var' => 'googleplus', 'val' => '');
        $dashicons[] = array('var' => 'networking', 'val' => '');
        $dashicons[] = array('var' => 'hammer', 'val' => '');
        $dashicons[] = array('var' => 'art', 'val' => '');
        $dashicons[] = array('var' => 'migrate', 'val' => '');
        $dashicons[] = array('var' => 'performance', 'val' => '');
        $dashicons[] = array('var' => 'universal-access', 'val' => '');
        $dashicons[] = array('var' => 'universal-access-alt', 'val' => '');
        $dashicons[] = array('var' => 'tickets', 'val' => '');
        $dashicons[] = array('var' => 'nametag', 'val' => '');
        $dashicons[] = array('var' => 'clipboard', 'val' => '');
        $dashicons[] = array('var' => 'heart', 'val' => '');
        $dashicons[] = array('var' => 'megaphone', 'val' => '');
        $dashicons[] = array('var' => 'schedule', 'val' => '');
        $dashicons[] = array('var' => 'wordpress', 'val' => '');
        $dashicons[] = array('var' => 'wordpress-alt', 'val' => '');
        $dashicons[] = array('var' => 'pressthis', 'val' => '');
        $dashicons[] = array('var' => 'update', 'val' => '');
        $dashicons[] = array('var' => 'screenoptions', 'val' => '');
        $dashicons[] = array('var' => 'info', 'val' => '');
        $dashicons[] = array('var' => 'cart', 'val' => '');
        $dashicons[] = array('var' => 'feedback', 'val' => '');
        $dashicons[] = array('var' => 'cloud', 'val' => '');
        $dashicons[] = array('var' => 'translation', 'val' => '');
        $dashicons[] = array('var' => 'tag', 'val' => '');
        $dashicons[] = array('var' => 'category', 'val' => '');
        $dashicons[] = array('var' => 'archive', 'val' => '');
        $dashicons[] = array('var' => 'tagcloud', 'val' => '');
        $dashicons[] = array('var' => 'text', 'val' => '');
        $dashicons[] = array('var' => 'yes', 'val' => '');
        $dashicons[] = array('var' => 'no', 'val' => '');
        $dashicons[] = array('var' => 'no-alt', 'val' => '');
        $dashicons[] = array('var' => 'plus', 'val' => '');
        $dashicons[] = array('var' => 'plus-alt', 'val' => '');
        $dashicons[] = array('var' => 'minus', 'val' => '');
        $dashicons[] = array('var' => 'dismiss', 'val' => '');
        $dashicons[] = array('var' => 'marker', 'val' => '');
        $dashicons[] = array('var' => 'star-filled', 'val' => '');
        $dashicons[] = array('var' => 'star-half', 'val' => '');
        $dashicons[] = array('var' => 'star-empty', 'val' => '');
        $dashicons[] = array('var' => 'flag', 'val' => '');
        $dashicons[] = array('var' => 'warning', 'val' => '');
        $dashicons[] = array('var' => 'location', 'val' => '');
        $dashicons[] = array('var' => 'location-alt', 'val' => '');
        $dashicons[] = array('var' => 'vault', 'val' => '');
        $dashicons[] = array('var' => 'shield', 'val' => '');
        $dashicons[] = array('var' => 'shield-alt', 'val' => '');
        $dashicons[] = array('var' => 'sos', 'val' => '');
        $dashicons[] = array('var' => 'search', 'val' => '');
        $dashicons[] = array('var' => 'slides', 'val' => '');
        $dashicons[] = array('var' => 'analytics', 'val' => '');
        $dashicons[] = array('var' => 'chart-pie', 'val' => '');
        $dashicons[] = array('var' => 'chart-bar', 'val' => '');
        $dashicons[] = array('var' => 'chart-line', 'val' => '');
        $dashicons[] = array('var' => 'chart-area', 'val' => '');
        $dashicons[] = array('var' => 'groups', 'val' => '');
        $dashicons[] = array('var' => 'businessman', 'val' => '');
        $dashicons[] = array('var' => 'id', 'val' => '');
        $dashicons[] = array('var' => 'id-alt', 'val' => '');
        $dashicons[] = array('var' => 'products', 'val' => '');
        $dashicons[] = array('var' => 'awards', 'val' => '');
        $dashicons[] = array('var' => 'forms', 'val' => '');
        $dashicons[] = array('var' => 'testimonial', 'val' => '');
        $dashicons[] = array('var' => 'portfolio', 'val' => '');
        $dashicons[] = array('var' => 'book', 'val' => '');
        $dashicons[] = array('var' => 'book-alt', 'val' => '');
        $dashicons[] = array('var' => 'download', 'val' => '');
        $dashicons[] = array('var' => 'upload', 'val' => '');
        $dashicons[] = array('var' => 'backup', 'val' => '');
        $dashicons[] = array('var' => 'clock', 'val' => '');
        $dashicons[] = array('var' => 'lightbulb', 'val' => '');
        $dashicons[] = array('var' => 'microphone', 'val' => '');
        $dashicons[] = array('var' => 'desktop', 'val' => '');
        $dashicons[] = array('var' => 'tablet', 'val' => '');
        $dashicons[] = array('var' => 'smartphone', 'val' => '');
        $dashicons[] = array('var' => 'phone', 'val' => '');
        $dashicons[] = array('var' => 'index-card', 'val' => '');
        $dashicons[] = array('var' => 'carrot', 'val' => '');
        $dashicons[] = array('var' => 'building', 'val' => '');
        $dashicons[] = array('var' => 'store', 'val' => '');
        $dashicons[] = array('var' => 'album', 'val' => '');
        $dashicons[] = array('var' => 'palmtree', 'val' => '');
        $dashicons[] = array('var' => 'tickets-alt', 'val' => '');
        $dashicons[] = array('var' => 'money', 'val' => '');
        $dashicons[] = array('var' => 'smiley', 'val' => '');
        $dashicons[] = array('var' => 'thumbs-up', 'val' => '');
        $dashicons[] = array('var' => 'thumbs-down', 'val' => '');
        $dashicons[] = array('var' => 'layout', 'val' => '');
        return $dashicons;
    }

    /**
     * ShowIcon::ElementorIcons()
     * 
     * @return void
     */
    function elementorIcons()
    {
        $elementor_icons = array();

        $elementor_icons[] = array('var' => 'editor-link', 'val' => '59392');
        $elementor_icons[] = array('var' => 'editor-unlink', 'val' => '59393');
        $elementor_icons[] = array('var' => 'editor-external-link', 'val' => '59394');
        $elementor_icons[] = array('var' => 'editor-close', 'val' => '59395');
        $elementor_icons[] = array('var' => 'editor-list-ol', 'val' => '59396');
        $elementor_icons[] = array('var' => 'editor-list-ul', 'val' => '59397');
        $elementor_icons[] = array('var' => 'editor-bold', 'val' => '59398');
        $elementor_icons[] = array('var' => 'editor-italic', 'val' => '59399');
        $elementor_icons[] = array('var' => 'editor-underline', 'val' => '59400');
        $elementor_icons[] = array('var' => 'editor-paragraph', 'val' => '59401');
        $elementor_icons[] = array('var' => 'editor-h1', 'val' => '59402');
        $elementor_icons[] = array('var' => 'editor-h2', 'val' => '59403');
        $elementor_icons[] = array('var' => 'editor-h3', 'val' => '59404');
        $elementor_icons[] = array('var' => 'editor-h4', 'val' => '59405');
        $elementor_icons[] = array('var' => 'editor-h5', 'val' => '59406');
        $elementor_icons[] = array('var' => 'editor-h6', 'val' => '59407');
        $elementor_icons[] = array('var' => 'editor-quote', 'val' => '59408');
        $elementor_icons[] = array('var' => 'editor-code', 'val' => '59409');
        $elementor_icons[] = array('var' => 'elementor', 'val' => '59410');
        $elementor_icons[] = array('var' => 'elementor-circle', 'val' => '59411');
        $elementor_icons[] = array('var' => 'pojome', 'val' => '59412');
        $elementor_icons[] = array('var' => 'plus', 'val' => '59413');
        $elementor_icons[] = array('var' => 'menu-bar', 'val' => '59414');
        $elementor_icons[] = array('var' => 'apps', 'val' => '59415');
        $elementor_icons[] = array('var' => 'accordion', 'val' => '59416');
        $elementor_icons[] = array('var' => 'alert', 'val' => '59417');
        $elementor_icons[] = array('var' => 'animation-text', 'val' => '59418');
        $elementor_icons[] = array('var' => 'animation', 'val' => '59419');
        $elementor_icons[] = array('var' => 'banner', 'val' => '59420');
        $elementor_icons[] = array('var' => 'blockquote', 'val' => '59421');
        $elementor_icons[] = array('var' => 'button', 'val' => '59422');
        $elementor_icons[] = array('var' => 'call-to-action', 'val' => '59423');
        $elementor_icons[] = array('var' => 'captcha', 'val' => '59424');
        $elementor_icons[] = array('var' => 'carousel', 'val' => '59425');
        $elementor_icons[] = array('var' => 'checkbox', 'val' => '59426');
        $elementor_icons[] = array('var' => 'columns', 'val' => '59427');
        $elementor_icons[] = array('var' => 'countdown', 'val' => '59428');
        $elementor_icons[] = array('var' => 'counter', 'val' => '59429');
        $elementor_icons[] = array('var' => 'date', 'val' => '59430');
        $elementor_icons[] = array('var' => 'divider-shape', 'val' => '59431');
        $elementor_icons[] = array('var' => 'divider', 'val' => '59432');
        $elementor_icons[] = array('var' => 'download-button', 'val' => '59433');
        $elementor_icons[] = array('var' => 'dual-button', 'val' => '59434');
        $elementor_icons[] = array('var' => 'email-field', 'val' => '59435');
        $elementor_icons[] = array('var' => 'facebook-comments', 'val' => '59436');
        $elementor_icons[] = array('var' => 'facebook-like-box', 'val' => '59437');
        $elementor_icons[] = array('var' => 'form-horizontal', 'val' => '59438');
        $elementor_icons[] = array('var' => 'form-vertical', 'val' => '59439');
        $elementor_icons[] = array('var' => 'gallery-grid', 'val' => '59440');
        $elementor_icons[] = array('var' => 'gallery-group', 'val' => '59441');
        $elementor_icons[] = array('var' => 'gallery-justified', 'val' => '59442');
        $elementor_icons[] = array('var' => 'gallery-masonry', 'val' => '59443');
        $elementor_icons[] = array('var' => 'icon-box', 'val' => '59444');
        $elementor_icons[] = array('var' => 'image-before-after', 'val' => '59445');
        $elementor_icons[] = array('var' => 'image-box', 'val' => '59446');
        $elementor_icons[] = array('var' => 'image-hotspot', 'val' => '59447');
        $elementor_icons[] = array('var' => 'image-rollover', 'val' => '59448');
        $elementor_icons[] = array('var' => 'info-box', 'val' => '59449');
        $elementor_icons[] = array('var' => 'inner-section', 'val' => '59450');
        $elementor_icons[] = array('var' => 'mailchimp', 'val' => '59451');
        $elementor_icons[] = array('var' => 'menu-card', 'val' => '59452');
        $elementor_icons[] = array('var' => 'navigation-horizontal', 'val' => '59453');
        $elementor_icons[] = array('var' => 'nav-menu', 'val' => '59454');
        $elementor_icons[] = array('var' => 'navigation-vertical', 'val' => '59455');
        $elementor_icons[] = array('var' => 'number-field', 'val' => '59456');
        $elementor_icons[] = array('var' => 'parallax', 'val' => '59457');
        $elementor_icons[] = array('var' => 'php7', 'val' => '59458');
        $elementor_icons[] = array('var' => 'post-list', 'val' => '59459');
        $elementor_icons[] = array('var' => 'post-slider', 'val' => '59460');
        $elementor_icons[] = array('var' => 'post', 'val' => '59461');
        $elementor_icons[] = array('var' => 'posts-carousel', 'val' => '59462');
        $elementor_icons[] = array('var' => 'posts-grid', 'val' => '59463');
        $elementor_icons[] = array('var' => 'posts-group', 'val' => '59464');
        $elementor_icons[] = array('var' => 'posts-justified', 'val' => '59465');
        $elementor_icons[] = array('var' => 'posts-masonry', 'val' => '59466');
        $elementor_icons[] = array('var' => 'posts-ticker', 'val' => '59467');
        $elementor_icons[] = array('var' => 'price-list', 'val' => '59468');
        $elementor_icons[] = array('var' => 'price-table', 'val' => '59469');
        $elementor_icons[] = array('var' => 'radio', 'val' => '59470');
        $elementor_icons[] = array('var' => 'rtl', 'val' => '59471');
        $elementor_icons[] = array('var' => 'scroll', 'val' => '59472');
        $elementor_icons[] = array('var' => 'search', 'val' => '59473');
        $elementor_icons[] = array('var' => 'select', 'val' => '59474');
        $elementor_icons[] = array('var' => 'share', 'val' => '59475');
        $elementor_icons[] = array('var' => 'sidebar', 'val' => '59476');
        $elementor_icons[] = array('var' => 'skill-bar', 'val' => '59477');
        $elementor_icons[] = array('var' => 'slider-3d', 'val' => '59478');
        $elementor_icons[] = array('var' => 'slider-album', 'val' => '59479');
        $elementor_icons[] = array('var' => 'slider-device', 'val' => '59480');
        $elementor_icons[] = array('var' => 'slider-full-screen', 'val' => '59481');
        $elementor_icons[] = array('var' => 'slider-push', 'val' => '59482');
        $elementor_icons[] = array('var' => 'slider-vertical', 'val' => '59483');
        $elementor_icons[] = array('var' => 'slider-video', 'val' => '59484');
        $elementor_icons[] = array('var' => 'slides', 'val' => '59485');
        $elementor_icons[] = array('var' => 'social-icons', 'val' => '59486');
        $elementor_icons[] = array('var' => 'spacer', 'val' => '59487');
        $elementor_icons[] = array('var' => 'table', 'val' => '59488');
        $elementor_icons[] = array('var' => 'tabs', 'val' => '59489');
        $elementor_icons[] = array('var' => 'tel-field', 'val' => '59490');
        $elementor_icons[] = array('var' => 'text-area', 'val' => '59491');
        $elementor_icons[] = array('var' => 'text-field', 'val' => '59492');
        $elementor_icons[] = array('var' => 'thumbnails-down', 'val' => '59493');
        $elementor_icons[] = array('var' => 'thumbnails-half', 'val' => '59494');
        $elementor_icons[] = array('var' => 'thumbnails-right', 'val' => '59495');
        $elementor_icons[] = array('var' => 'time-line', 'val' => '59496');
        $elementor_icons[] = array('var' => 'toggle', 'val' => '59497');
        $elementor_icons[] = array('var' => 'url', 'val' => '59498');
        $elementor_icons[] = array('var' => 't-letter', 'val' => '59499');
        $elementor_icons[] = array('var' => 'wordpress', 'val' => '59500');
        $elementor_icons[] = array('var' => 'text', 'val' => '59501');
        $elementor_icons[] = array('var' => 'anchor', 'val' => '59502');
        $elementor_icons[] = array('var' => 'bullet-list', 'val' => '59503');
        $elementor_icons[] = array('var' => 'code', 'val' => '59504');
        $elementor_icons[] = array('var' => 'favorite', 'val' => '59505');
        $elementor_icons[] = array('var' => 'google-maps', 'val' => '59506');
        $elementor_icons[] = array('var' => 'image', 'val' => '59507');
        $elementor_icons[] = array('var' => 'photo-library', 'val' => '59508');
        $elementor_icons[] = array('var' => 'woocommerce', 'val' => '59509');
        $elementor_icons[] = array('var' => 'youtube', 'val' => '59510');
        $elementor_icons[] = array('var' => 'flip-box', 'val' => '59511');
        $elementor_icons[] = array('var' => 'settings', 'val' => '59512');
        $elementor_icons[] = array('var' => 'headphones', 'val' => '59513');
        $elementor_icons[] = array('var' => 'testimonial', 'val' => '59514');
        $elementor_icons[] = array('var' => 'counter-circle', 'val' => '59515');
        $elementor_icons[] = array('var' => 'person', 'val' => '59516');
        $elementor_icons[] = array('var' => 'chevron-right', 'val' => '59517');
        $elementor_icons[] = array('var' => 'chevron-left', 'val' => '59518');
        $elementor_icons[] = array('var' => 'close', 'val' => '59519');
        $elementor_icons[] = array('var' => 'file-download', 'val' => '59520');
        $elementor_icons[] = array('var' => 'save', 'val' => '59521');
        $elementor_icons[] = array('var' => 'zoom-in', 'val' => '59522');
        $elementor_icons[] = array('var' => 'shortcode', 'val' => '59523');
        $elementor_icons[] = array('var' => 'nerd', 'val' => '59524');
        $elementor_icons[] = array('var' => 'device-desktop', 'val' => '59525');
        $elementor_icons[] = array('var' => 'device-tablet', 'val' => '59526');
        $elementor_icons[] = array('var' => 'device-mobile', 'val' => '59527');
        $elementor_icons[] = array('var' => 'document-file', 'val' => '59528');
        $elementor_icons[] = array('var' => 'folder-o', 'val' => '59529');
        $elementor_icons[] = array('var' => 'hypster', 'val' => '59530');
        $elementor_icons[] = array('var' => 'h-align-left', 'val' => '59531');
        $elementor_icons[] = array('var' => 'h-align-right', 'val' => '59532');
        $elementor_icons[] = array('var' => 'h-align-center', 'val' => '59533');
        $elementor_icons[] = array('var' => 'h-align-stretch', 'val' => '59534');
        $elementor_icons[] = array('var' => 'v-align-top', 'val' => '59535');
        $elementor_icons[] = array('var' => 'v-align-bottom', 'val' => '59536');
        $elementor_icons[] = array('var' => 'v-align-middle', 'val' => '59537');
        $elementor_icons[] = array('var' => 'v-align-stretch', 'val' => '59538');
        $elementor_icons[] = array('var' => 'pro-icon', 'val' => '59539');
        $elementor_icons[] = array('var' => 'mail', 'val' => '59540');
        $elementor_icons[] = array('var' => 'lock-user', 'val' => '59541');
        $elementor_icons[] = array('var' => 'testimonial-carousel', 'val' => '59542');
        $elementor_icons[] = array('var' => 'media-carousel', 'val' => '59543');
        $elementor_icons[] = array('var' => 'section', 'val' => '59544');
        $elementor_icons[] = array('var' => 'column', 'val' => '59545');
        $elementor_icons[] = array('var' => 'edit', 'val' => '59546');
        $elementor_icons[] = array('var' => 'clone', 'val' => '59547');
        $elementor_icons[] = array('var' => 'trash', 'val' => '59548');
        $elementor_icons[] = array('var' => 'play', 'val' => '59549');
        $elementor_icons[] = array('var' => 'angle-right', 'val' => '59550');
        $elementor_icons[] = array('var' => 'angle-left', 'val' => '59551');
        $elementor_icons[] = array('var' => 'animated-headline', 'val' => '59552');
        $elementor_icons[] = array('var' => 'menu-toggle', 'val' => '59553');
        $elementor_icons[] = array('var' => 'fb-embed', 'val' => '59554');
        $elementor_icons[] = array('var' => 'fb-feed', 'val' => '59555');
        $elementor_icons[] = array('var' => 'twitter-embed', 'val' => '59556');
        $elementor_icons[] = array('var' => 'twitter-feed', 'val' => '59557');
        $elementor_icons[] = array('var' => 'sync', 'val' => '59558');
        $elementor_icons[] = array('var' => 'import-export', 'val' => '59559');
        $elementor_icons[] = array('var' => 'check-circle', 'val' => '59560');
        $elementor_icons[] = array('var' => 'library-save', 'val' => '59561');
        $elementor_icons[] = array('var' => 'library-download', 'val' => '59562');
        $elementor_icons[] = array('var' => 'insert', 'val' => '59563');
        $elementor_icons[] = array('var' => 'preview-medium', 'val' => '59564');
        $elementor_icons[] = array('var' => 'sort-down', 'val' => '59565');
        $elementor_icons[] = array('var' => 'sort-up', 'val' => '59566');
        $elementor_icons[] = array('var' => 'heading', 'val' => '59567');
        $elementor_icons[] = array('var' => 'logo', 'val' => '59568');
        $elementor_icons[] = array('var' => 'meta-data', 'val' => '59569');
        $elementor_icons[] = array('var' => 'post-content', 'val' => '59570');
        $elementor_icons[] = array('var' => 'post-excerpt', 'val' => '59571');
        $elementor_icons[] = array('var' => 'post-navigation', 'val' => '59572');
        $elementor_icons[] = array('var' => 'yoast', 'val' => '59573');
        $elementor_icons[] = array('var' => 'nerd-chuckle', 'val' => '59574');
        $elementor_icons[] = array('var' => 'nerd-wink', 'val' => '59575');
        $elementor_icons[] = array('var' => 'comments', 'val' => '59576');
        $elementor_icons[] = array('var' => 'download-circle-o', 'val' => '59577');
        $elementor_icons[] = array('var' => 'library-upload', 'val' => '59578');
        $elementor_icons[] = array('var' => 'save-o', 'val' => '59579');
        $elementor_icons[] = array('var' => 'upload-circle-o', 'val' => '59580');
        $elementor_icons[] = array('var' => 'ellipsis-h', 'val' => '59581');
        $elementor_icons[] = array('var' => 'ellipsis-v', 'val' => '59582');
        $elementor_icons[] = array('var' => 'arrow-left', 'val' => '59583');
        $elementor_icons[] = array('var' => 'arrow-right', 'val' => '59584');
        $elementor_icons[] = array('var' => 'arrow-up', 'val' => '59585');
        $elementor_icons[] = array('var' => 'arrow-down', 'val' => '59586');
        $elementor_icons[] = array('var' => 'play-o', 'val' => '59587');
        $elementor_icons[] = array('var' => 'archive-posts', 'val' => '59588');
        $elementor_icons[] = array('var' => 'archive-title', 'val' => '59589');
        $elementor_icons[] = array('var' => 'featured-image', 'val' => '59590');
        $elementor_icons[] = array('var' => 'post-info', 'val' => '59591');
        $elementor_icons[] = array('var' => 'post-title', 'val' => '59592');
        $elementor_icons[] = array('var' => 'site-logo', 'val' => '59593');
        $elementor_icons[] = array('var' => 'site-search', 'val' => '59594');
        $elementor_icons[] = array('var' => 'site-title', 'val' => '59595');
        $elementor_icons[] = array('var' => 'plus-square', 'val' => '59596');
        $elementor_icons[] = array('var' => 'minus-square', 'val' => '59597');
        $elementor_icons[] = array('var' => 'cloud-check', 'val' => '59598');
        $elementor_icons[] = array('var' => 'drag-n-drop', 'val' => '59599');
        $elementor_icons[] = array('var' => 'welcome', 'val' => '59600');
        $elementor_icons[] = array('var' => 'handle', 'val' => '59601');
        $elementor_icons[] = array('var' => 'cart', 'val' => '59602');
        $elementor_icons[] = array('var' => 'product-add-to-cart', 'val' => '59603');
        $elementor_icons[] = array('var' => 'product-breadcrumbs', 'val' => '59604');
        $elementor_icons[] = array('var' => 'product-categories', 'val' => '59605');
        $elementor_icons[] = array('var' => 'product-description', 'val' => '59606');
        $elementor_icons[] = array('var' => 'product-images', 'val' => '59607');
        $elementor_icons[] = array('var' => 'product-info', 'val' => '59608');
        $elementor_icons[] = array('var' => 'product-meta', 'val' => '59609');
        $elementor_icons[] = array('var' => 'product-pages', 'val' => '59610');
        $elementor_icons[] = array('var' => 'product-price', 'val' => '59611');
        $elementor_icons[] = array('var' => 'product-rating', 'val' => '59612');
        $elementor_icons[] = array('var' => 'product-related', 'val' => '59613');
        $elementor_icons[] = array('var' => 'product-stock', 'val' => '59614');
        $elementor_icons[] = array('var' => 'product-tabs', 'val' => '59615');
        $elementor_icons[] = array('var' => 'product-title', 'val' => '59616');
        $elementor_icons[] = array('var' => 'product-upsell', 'val' => '59617');
        $elementor_icons[] = array('var' => 'products', 'val' => '59618');
        $elementor_icons[] = array('var' => 'bag-light', 'val' => '59619');
        $elementor_icons[] = array('var' => 'bag-medium', 'val' => '59620');
        $elementor_icons[] = array('var' => 'bag-solid', 'val' => '59621');
        $elementor_icons[] = array('var' => 'basket-light', 'val' => '59622');
        $elementor_icons[] = array('var' => 'basket-medium', 'val' => '59623');
        $elementor_icons[] = array('var' => 'basket-solid', 'val' => '59624');
        $elementor_icons[] = array('var' => 'cart-light', 'val' => '59625');
        $elementor_icons[] = array('var' => 'cart-medium', 'val' => '59626');
        $elementor_icons[] = array('var' => 'cart-solid', 'val' => '59627');
        $elementor_icons[] = array('var' => 'exchange', 'val' => '59628');
        $elementor_icons[] = array('var' => 'preview-thin', 'val' => '59629');
        $elementor_icons[] = array('var' => 'device-laptop', 'val' => '59630');
        $elementor_icons[] = array('var' => 'collapse', 'val' => '59631');
        $elementor_icons[] = array('var' => 'expand', 'val' => '59632');
        $elementor_icons[] = array('var' => 'navigator', 'val' => '59633');
        $elementor_icons[] = array('var' => 'plug', 'val' => '59634');
        $elementor_icons[] = array('var' => 'dashboard', 'val' => '59635');
        $elementor_icons[] = array('var' => 'typography', 'val' => '59636');
        $elementor_icons[] = array('var' => 'info-circle-o', 'val' => '59637');
        $elementor_icons[] = array('var' => 'integration', 'val' => '59638');
        $elementor_icons[] = array('var' => 'plus-circle-o', 'val' => '59639');
        $elementor_icons[] = array('var' => 'rating', 'val' => '59640');
        $elementor_icons[] = array('var' => 'review', 'val' => '59641');
        $elementor_icons[] = array('var' => 'tools', 'val' => '59642');
        $elementor_icons[] = array('var' => 'loading', 'val' => '59643');
        $elementor_icons[] = array('var' => 'sitemap', 'val' => '59644');
        $elementor_icons[] = array('var' => 'click', 'val' => '59645');
        $elementor_icons[] = array('var' => 'clock', 'val' => '59646');
        $elementor_icons[] = array('var' => 'library-open', 'val' => '59647');
        $elementor_icons[] = array('var' => 'warning', 'val' => '59648');
        $elementor_icons[] = array('var' => 'flow', 'val' => '59649');
        $elementor_icons[] = array('var' => 'cursor-move', 'val' => '59650');
        $elementor_icons[] = array('var' => 'arrow-circle-left', 'val' => '59651');
        $elementor_icons[] = array('var' => 'flash', 'val' => '59652');
        $elementor_icons[] = array('var' => 'redo', 'val' => '59653');
        $elementor_icons[] = array('var' => 'ban', 'val' => '59654');
        $elementor_icons[] = array('var' => 'barcode', 'val' => '59655');
        $elementor_icons[] = array('var' => 'calendar', 'val' => '59656');
        $elementor_icons[] = array('var' => 'caret-left', 'val' => '59657');
        $elementor_icons[] = array('var' => 'caret-right', 'val' => '59658');
        $elementor_icons[] = array('var' => 'caret-up', 'val' => '59659');
        $elementor_icons[] = array('var' => 'chain-broken', 'val' => '59660');
        $elementor_icons[] = array('var' => 'check-circle-o', 'val' => '59661');
        $elementor_icons[] = array('var' => 'check', 'val' => '59662');
        $elementor_icons[] = array('var' => 'chevron-double-left', 'val' => '59663');
        $elementor_icons[] = array('var' => 'chevron-double-right', 'val' => '59664');
        $elementor_icons[] = array('var' => 'undo', 'val' => '59665');
        $elementor_icons[] = array('var' => 'filter', 'val' => '59666');
        $elementor_icons[] = array('var' => 'circle-o', 'val' => '59667');
        $elementor_icons[] = array('var' => 'circle', 'val' => '59668');
        $elementor_icons[] = array('var' => 'clock-o', 'val' => '59669');
        $elementor_icons[] = array('var' => 'cog', 'val' => '59670');
        $elementor_icons[] = array('var' => 'cogs', 'val' => '59671');
        $elementor_icons[] = array('var' => 'commenting-o', 'val' => '59672');
        $elementor_icons[] = array('var' => 'copy', 'val' => '59673');
        $elementor_icons[] = array('var' => 'database', 'val' => '59674');
        $elementor_icons[] = array('var' => 'dot-circle-o', 'val' => '59675');
        $elementor_icons[] = array('var' => 'envelope', 'val' => '59676');
        $elementor_icons[] = array('var' => 'external-link-square', 'val' => '59677');
        $elementor_icons[] = array('var' => 'eyedropper', 'val' => '59678');
        $elementor_icons[] = array('var' => 'folder', 'val' => '59679');
        $elementor_icons[] = array('var' => 'font', 'val' => '59680');
        $elementor_icons[] = array('var' => 'adjust', 'val' => '59681');
        $elementor_icons[] = array('var' => 'lightbox', 'val' => '59682');
        $elementor_icons[] = array('var' => 'heart-o', 'val' => '59683');
        $elementor_icons[] = array('var' => 'history', 'val' => '59684');
        $elementor_icons[] = array('var' => 'image-bold', 'val' => '59685');
        $elementor_icons[] = array('var' => 'info-circle', 'val' => '59686');
        $elementor_icons[] = array('var' => 'link', 'val' => '59687');
        $elementor_icons[] = array('var' => 'long-arrow-left', 'val' => '59688');
        $elementor_icons[] = array('var' => 'long-arrow-right', 'val' => '59689');
        $elementor_icons[] = array('var' => 'caret-down', 'val' => '59690');
        $elementor_icons[] = array('var' => 'paint-brush', 'val' => '59691');
        $elementor_icons[] = array('var' => 'pencil', 'val' => '59692');
        $elementor_icons[] = array('var' => 'plus-circle', 'val' => '59693');
        $elementor_icons[] = array('var' => 'zoom-in-bold', 'val' => '59694');
        $elementor_icons[] = array('var' => 'sort-amount-desc', 'val' => '59695');
        $elementor_icons[] = array('var' => 'sign-out', 'val' => '59696');
        $elementor_icons[] = array('var' => 'spinner', 'val' => '59697');
        $elementor_icons[] = array('var' => 'square', 'val' => '59698');
        $elementor_icons[] = array('var' => 'star-o', 'val' => '59699');
        $elementor_icons[] = array('var' => 'star', 'val' => '59700');
        $elementor_icons[] = array('var' => 'text-align-justify', 'val' => '59701');
        $elementor_icons[] = array('var' => 'text-align-center', 'val' => '59702');
        $elementor_icons[] = array('var' => 'tags', 'val' => '59703');
        $elementor_icons[] = array('var' => 'text-align-left', 'val' => '59704');
        $elementor_icons[] = array('var' => 'text-align-right', 'val' => '59705');
        $elementor_icons[] = array('var' => 'close-circle', 'val' => '59706');
        $elementor_icons[] = array('var' => 'trash-o', 'val' => '59707');
        $elementor_icons[] = array('var' => 'font-awesome', 'val' => '59708');
        $elementor_icons[] = array('var' => 'user-circle-o', 'val' => '59709');
        $elementor_icons[] = array('var' => 'video-camera', 'val' => '59710');
        $elementor_icons[] = array('var' => 'heart', 'val' => '59711');
        $elementor_icons[] = array('var' => 'wrench', 'val' => '59712');
        $elementor_icons[] = array('var' => 'help', 'val' => '59713');
        $elementor_icons[] = array('var' => 'help-o', 'val' => '59714');
        $elementor_icons[] = array('var' => 'zoom-out-bold', 'val' => '59715');
        $elementor_icons[] = array('var' => 'plus-square-o', 'val' => '59716');
        $elementor_icons[] = array('var' => 'minus-square-o', 'val' => '59717');
        $elementor_icons[] = array('var' => 'minus-circle', 'val' => '59718');
        $elementor_icons[] = array('var' => 'minus-circle-o', 'val' => '59719');
        $elementor_icons[] = array('var' => 'code-bold', 'val' => '59720');
        $elementor_icons[] = array('var' => 'cloud-upload', 'val' => '59721');
        $elementor_icons[] = array('var' => 'search-bold', 'val' => '59722');
        $elementor_icons[] = array('var' => 'map-pin', 'val' => '59723');
        $elementor_icons[] = array('var' => 'meetup', 'val' => '59724');
        $elementor_icons[] = array('var' => 'slideshow', 'val' => '59725');
        $elementor_icons[] = array('var' => 't-letter-bold', 'val' => '59726');
        $elementor_icons[] = array('var' => 'preferences', 'val' => '59727');
        $elementor_icons[] = array('var' => 'table-of-contents', 'val' => '59728');
        $elementor_icons[] = array('var' => 'tv', 'val' => '59729');
        $elementor_icons[] = array('var' => 'upload', 'val' => '59730');
        $elementor_icons[] = array('var' => 'instagram-comments', 'val' => '59731');
        $elementor_icons[] = array('var' => 'instagram-nested-gallery', 'val' => '59732');
        $elementor_icons[] = array('var' => 'instagram-post', 'val' => '59733');
        $elementor_icons[] = array('var' => 'instagram-video', 'val' => '59734');
        $elementor_icons[] = array('var' => 'instagram-gallery', 'val' => '59735');
        $elementor_icons[] = array('var' => 'instagram-likes', 'val' => '59736');
        $elementor_icons[] = array('var' => 'facebook', 'val' => '59737');
        $elementor_icons[] = array('var' => 'twitter', 'val' => '59738');
        $elementor_icons[] = array('var' => 'pinterest', 'val' => '59739');
        $elementor_icons[] = array('var' => 'frame-expand', 'val' => '59740');
        $elementor_icons[] = array('var' => 'frame-minimize', 'val' => '59741');
        $elementor_icons[] = array('var' => 'archive', 'val' => '59742');
        $elementor_icons[] = array('var' => 'colors-typography', 'val' => '59743');
        $elementor_icons[] = array('var' => 'custom', 'val' => '59744');
        $elementor_icons[] = array('var' => 'footer', 'val' => '59745');
        $elementor_icons[] = array('var' => 'header', 'val' => '59746');
        $elementor_icons[] = array('var' => 'layout-settings', 'val' => '59747');
        $elementor_icons[] = array('var' => 'lightbox-expand', 'val' => '59748');
        $elementor_icons[] = array('var' => 'error-404', 'val' => '59749');
        $elementor_icons[] = array('var' => 'theme-style', 'val' => '59750');
        $elementor_icons[] = array('var' => 'search-results', 'val' => '59751');
        $elementor_icons[] = array('var' => 'single-post', 'val' => '59752');
        $elementor_icons[] = array('var' => 'site-identity', 'val' => '59753');
        $elementor_icons[] = array('var' => 'theme-builder', 'val' => '59754');
        $elementor_icons[] = array('var' => 'download-bold', 'val' => '59755');
        $elementor_icons[] = array('var' => 'share-arrow', 'val' => '59756');
        $elementor_icons[] = array('var' => 'global-settings', 'val' => '59757');
        $elementor_icons[] = array('var' => 'user-preferences', 'val' => '59758');
        $elementor_icons[] = array('var' => 'lock', 'val' => '59759');
        $elementor_icons[] = array('var' => 'export-kit', 'val' => '59760');
        $elementor_icons[] = array('var' => 'import-kit', 'val' => '59761');
        $elementor_icons[] = array('var' => 'lottie', 'val' => '59762');
        $elementor_icons[] = array('var' => 'products-archive', 'val' => '59763');
        $elementor_icons[] = array('var' => 'single-product', 'val' => '59764');
        $elementor_icons[] = array('var' => 'disable-trash-o', 'val' => '59765');
        $elementor_icons[] = array('var' => 'single-page', 'val' => '59766');
        $elementor_icons[] = array('var' => 'wordpress-light', 'val' => '59767');
        $elementor_icons[] = array('var' => 'cogs-check', 'val' => '59768');
        $elementor_icons[] = array('var' => 'custom-css', 'val' => '59769');
        $elementor_icons[] = array('var' => 'global-colors', 'val' => '59770');
        $elementor_icons[] = array('var' => 'globe', 'val' => '59771');
        $elementor_icons[] = array('var' => 'code-highlight', 'val' => '59776');
        $elementor_icons[] = array('var' => 'video-playlist', 'val' => '59777');
        $elementor_icons[] = array('var' => 'download-kit', 'val' => '59778');
        $elementor_icons[] = array('var' => 'kit-details', 'val' => '59779');
        $elementor_icons[] = array('var' => 'kit-parts', 'val' => '59780');
        $elementor_icons[] = array('var' => 'kit-upload', 'val' => '59781');
        $elementor_icons[] = array('var' => 'kit-plugins', 'val' => '59782');
        $elementor_icons[] = array('var' => 'kit-upload-alt', 'val' => '59783');
        $elementor_icons[] = array('var' => 'hotspot', 'val' => '59784');
        $elementor_icons[] = array('var' => 'paypal-button', 'val' => '59785');
        $elementor_icons[] = array('var' => 'shape', 'val' => '59786');
        $elementor_icons[] = array('var' => 'wordart', 'val' => '59787');
        $elementor_icons[] = array('var' => 'checkout', 'val' => '59788');
        $elementor_icons[] = array('var' => 'container', 'val' => '59789');
        $elementor_icons[] = array('var' => 'flip', 'val' => '59790');
        $elementor_icons[] = array('var' => 'info', 'val' => '59791');
        $elementor_icons[] = array('var' => 'my-account', 'val' => '59792');
        $elementor_icons[] = array('var' => 'purchase-summary', 'val' => '59793');
        $elementor_icons[] = array('var' => 'page-transition', 'val' => '59794');
        $elementor_icons[] = array('var' => 'spotify', 'val' => '59795');
        $elementor_icons[] = array('var' => 'stripe-button', 'val' => '59796');
        $elementor_icons[] = array('var' => 'woo-settings', 'val' => '59797');
        $elementor_icons[] = array('var' => 'woo-cart', 'val' => '59798');
        $elementor_icons[] = array('var' => 'typography-1', 'val' => '59772');
        $elementor_icons[] = array('var' => 'background', 'val' => '59773');
        $elementor_icons[] = array('var' => 'device-responsive', 'val' => '59774');
        $elementor_icons[] = array('var' => 'device-wide', 'val' => '59775');
        $elementor_icons[] = array('var' => 'grow', 'val' => '59799');
        $elementor_icons[] = array('var' => 'order-end', 'val' => '59800');
        $elementor_icons[] = array('var' => 'nowrap', 'val' => '59801');
        $elementor_icons[] = array('var' => 'order-start', 'val' => '59802');
        $elementor_icons[] = array('var' => 'progress-tracker', 'val' => '59803');
        $elementor_icons[] = array('var' => 'shrink', 'val' => '59804');
        $elementor_icons[] = array('var' => 'wrap', 'val' => '59805');
        $elementor_icons[] = array('var' => 'align-center-h', 'val' => '59806');
        $elementor_icons[] = array('var' => 'align-center-v', 'val' => '59807');
        $elementor_icons[] = array('var' => 'align-end-h', 'val' => '59808');
        $elementor_icons[] = array('var' => 'align-end-v', 'val' => '59809');
        $elementor_icons[] = array('var' => 'align-start-h', 'val' => '59810');
        $elementor_icons[] = array('var' => 'align-start-v', 'val' => '59811');
        $elementor_icons[] = array('var' => 'align-stretch-h', 'val' => '59812');
        $elementor_icons[] = array('var' => 'align-stretch-v', 'val' => '59813');
        $elementor_icons[] = array('var' => 'justify-center-h', 'val' => '59814');
        $elementor_icons[] = array('var' => 'justify-center-v', 'val' => '59815');
        $elementor_icons[] = array('var' => 'justify-end-h', 'val' => '59816');
        $elementor_icons[] = array('var' => 'justify-end-v', 'val' => '59817');
        $elementor_icons[] = array('var' => 'justify-space-around-h', 'val' => '59818');
        $elementor_icons[] = array('var' => 'justify-space-around-v', 'val' => '59819');
        $elementor_icons[] = array('var' => 'justify-space-between-h', 'val' => '59820');
        $elementor_icons[] = array('var' => 'justify-space-between-v', 'val' => '59821');
        $elementor_icons[] = array('var' => 'justify-space-evenly-h', 'val' => '59822');
        $elementor_icons[] = array('var' => 'justify-start-h', 'val' => '59824');
        $elementor_icons[] = array('var' => 'justify-start-v', 'val' => '59825');
        $elementor_icons[] = array('var' => 'justify-space-evenly-v', 'val' => '59823');
        $elementor_icons[] = array('var' => 'woocommerce-cross-sells', 'val' => '59826');
        $elementor_icons[] = array('var' => 'woocommerce-notices', 'val' => '59827');
        $elementor_icons[] = array('var' => 'inner-container', 'val' => '59828');
        $elementor_icons[] = array('var' => 'warning-full', 'val' => '59829');
        $elementor_icons[] = array('var' => 'exit', 'val' => '59830');


        return $elementor_icons;
    }

    function Display($prefix = 'dashicons', $title = 'Dashicons')
    {
        $html = null;
        $html .= '<div class="modal fade" id="' . $prefix . '-dialog" role="dialog" tabindex="-1" aria-hidden="true">';
        $html .= '<div class="modal-dialog modal-lg">';
        $html .= '<div class="modal-content">';

        $html .= '<div class="modal-header">';

        $html .= '<h5 class="modal-title" id="exampleModalLabel">' . $title . '</h5>';
        $html .= '<button type="button" class="close" data-dismiss="modal" aria-label="Close">';
        $html .= '<span aria-hidden="true">&times;</span>';
        $html .= '</button>';
        $html .= '</div>';

        $html .= '<div class="modal-body">';
        $html .= '<div class="form-group">';
        $html .= '<input type="text" class="form-control" id="filter-' . $prefix . '-icon" placeholder="Search Icon"/>';
        $html .= '</div>';
        $html .= '<div class="icon-box row">';
        switch ($prefix)
        {
            case 'dashicons':
                foreach ($this->dashicons() as $icon)
                {
                    $html .= '<div class="icon-item ' . $prefix . '-icon-item col-xs-1 col-md-1 col-lg-1" data-id="' . $icon['var'] . '">';
                    $html .= '<a data-toggle="tooltip" data-placement="top" title="' . $icon['var'] . '" href="#' . $icon['var'] . '" class="' . $prefix . '-icon-list icon-list" data-icon="' . $prefix . '-' . $icon['var'] . '">';
                    $html .= '<span class="icon ' . $prefix . ' ' . $prefix . '-' . $icon['var'] . '"></span>';
                    $html .= '</a>';
                    $html .= '</div>';
                }
                break;
            case 'eicon':
                foreach ($this->elementorIcons() as $icon)
                {
                    $html .= '<div class="icon-item ' . $prefix . '-icon-item col-xs-1 col-md-1 col-lg-1" data-id="' . $icon['var'] . '">';
                    $html .= '<a data-toggle="tooltip" data-placement="top" title="' . $icon['var'] . '" href="#' . $icon['var'] . '" class="' . $prefix . '-icon-list icon-list" data-icon="' . $prefix . '-' . $icon['var'] . '">';
                    $html .= '<span class="icon ' . $prefix . '-' . $icon['var'] . '"></span>';
                    $html .= '</a>';
                    $html .= '</div>';
                }

                break;
        }

        $html .= '</div>';
        $html .= '</div>';

        $html .= '<div class="modal-footer">';
        $html .= '<button type="button" id="modal-icon-dialog-button-dismiss"  class="btn btn-default btn-md" data-dismiss="modal">Close</button>';
        $html .= '</div>';

        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        return $html;
    }
}

?>